---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: tangle
description: GNU/Linux TangleOS - districando complessità con potenza atomica

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - kitty
        - git
        - fastfetch
        - plymouth-plugin-script
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-tour
        - ptyxis

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Showtime
          - org.gnome.Decibels
          - org.libreoffice.LibreOffice
          - org.gnome.Evolution
          - com.usebottles.bottles
          - com.brave.Browser

  - type: gschema-overrides
    include:
      - zz1-tangleos.gschema.override

  - type: script
    scripts:
      - tangleos-branding.sh

  - type: os-release
    properties:
      NAME: "TangleOS"
      PRETTY_NAME: "TangleOS 44 (Knot)"
      VERSION_CODENAME: "knot"
      LOGO: "distributor-logo-tangleos"
      DEFAULT_HOSTNAME: "tangle"
      ANSI_COLOR: "38;2;192;113;82"
      HOME_URL: "https://github.com/giacomogarbuglia/tangle"

  - type: initramfs

  - type: signing
