---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: tangle
description: GNU/Linux Tangle OS - districando complessità con potenza atomica

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - ashbuk/Hyprland-Fedora
    install:
      packages:
        - hyprland
        - xdg-desktop-portal-hyprland
        - waybar
        - mako
        - hyprlock
        - hypridle
        - rofi-wayland
        - grim
        - slurp
        - kitty
        - git
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Showtime
          - org.gnome.Decibels
          - org.libreoffice.LibreOffice
          - org.gnome.Evolution
          - com.usebottles.bottles
          - com.brave.Browser

  - type: signing
